import React from 'react';

interface TermsPageProps {
  onBack: () => void;
}

const TermsPage: React.FC<TermsPageProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-[#050509] text-gray-200 font-sans p-6 md:p-12 animate-fade-in">
      <div className="max-w-4xl mx-auto">
        <header className="flex items-center gap-4 mb-12">
           <button 
             onClick={onBack} 
             className="p-2 rounded-full bg-white/5 hover:bg-white/10 text-gray-400 hover:text-white transition-all duration-200 group"
             aria-label="Back"
           >
             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="group-hover:-translate-x-1 transition-transform"><path d="m15 18-6-6 6-6"/></svg>
           </button>
           <div>
             <h1 className="text-3xl font-bold text-gray-100">Terms of Service</h1>
             <p className="text-gray-500 mt-1">Last Updated: October 26, 2025</p>
           </div>
        </header>

        <div className="space-y-8 text-gray-300 leading-relaxed bg-[#10111a] p-8 rounded-xl border border-white/10 shadow-lg">
          
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Agreement to Terms</h2>
            <p>
              By accessing or using Fact Checker AI ("Service"), you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
            <p>
              Fact Checker AI provides AI-powered tools for information verification, logical analysis, and scam detection. We utilize advanced Large Language Models (LLMs) to process user queries and provide analysis based on available data.
            </p>
          </section>

          <section className="bg-yellow-900/10 border border-yellow-700/30 p-4 rounded-lg">
            <h2 className="text-xl font-bold text-yellow-500 mb-3">3. Disclaimer Regarding AI Accuracy</h2>
            <p className="text-yellow-100/80">
              <strong>Important:</strong> The output provided by Fact Checker AI is generated by artificial intelligence. While we strive for accuracy, AI models can produce errors, "hallucinations," or biased information. 
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2 text-yellow-100/80">
                <li>The Service should not be the sole basis for critical financial, medical, legal, or safety decisions.</li>
                <li>We do not guarantee the accuracy, completeness, or timeliness of any analysis provided.</li>
                <li>Users are responsible for verifying the information provided by the Service against primary sources.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Intellectual Property</h2>
            <p>
              The Service, including its original content, features, and functionality (excluding user-submitted content), is and will remain the exclusive property of Fact Checker AI and its developer, Samyak Kothare. The Service is protected by copyright, trademark, and other laws of both the local jurisdiction and foreign countries.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. User Conduct</h2>
            <p>You agree not to use the Service:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>In any way that violates any applicable national or international law or regulation.</li>
              <li>To transmit any material that is defamatory, obscene, indecent, abusive, offensive, harassing, violent, hateful, or otherwise objectionable.</li>
              <li>To attempt to reverse engineer, decompile, or disassemble any part of the Service.</li>
              <li>To use automated scripts or bots to access the Service without express written permission.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Limitation of Liability</h2>
            <p>
              In no event shall Fact Checker AI, its developers, directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
                <li>Your access to or use of or inability to access or use the Service;</li>
                <li>Any conduct or content of any third party on the Service;</li>
                <li>Any content obtained from the Service;</li>
                <li>Unauthorized access, use, or alteration of your transmissions or content.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Termination</h2>
            <p>
              We may terminate or suspend your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will cease immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="mt-2 font-mono text-[#f5c14b]">legal@factchecker-ai.com</p>
          </section>

        </div>
      </div>
    </div>
  );
};

export default TermsPage;